export const copy = {
  en: {
    htmlLang: "en",
    nav: { work: "Work", stack: "Stack", contact: "Contact" },
    heroKicker: "Linux host defense",
    heroTitle: "lifeqsoll",
    heroLead:
      "I study computer vision and build tools for Linux machines. The main one is SysSpectogram.",
    ctaGithub: "GitHub",
    ctaProject: "SysSpectogram",
    ctaTelegram: "Telegram",
    aboutIndex: "01",
    aboutTitle: "What I work on",
    aboutBody:
      "Computer vision, and models that read how a machine behaves. Convnets, classical models on tables, and the Linux tooling that ties them into one host utility.",
    workIndex: "02",
    workKicker: "MVP",
    workTitle: "SysSpectogram",
    workVersion: "v0.4",
    workLead:
      "An antivirus catches malware by a known file. A CPU or GPU miner, SSH password guesses, and odd outgoing traffic usually have no such file. SysSpectogram records how the machine behaves, turns one minute into a picture, and asks whether that minute looks like normal work.",
    problemTitle: "The point",
    problem:
      "Once a second it writes CPU, memory, disk, network, and GPU. Sixty seconds become one image. A small convnet reads the image. An isolation forest reads the same minute as a table. Together they say: this looks like everyday load, or like abuse.",
    tasksTitle: "What it takes on",
    tasks: [
      "Miners and odd load on CPU, memory, disk, network, and GPU.",
      "The edge of the host: password guesses, scans, outgoing traffic, DNS.",
      "Telegram and a web page. From there you can ban, look around, or kill a process. Nothing is applied until you confirm it.",
      "OSINT on the attacker IP: nmap, DNS, and certificate transparency.",
      "A Rust agent next to the model: processes, paths, modules, file integrity.",
    ],
    plateLabel: "How the number is made",
    plateFormula: "0.6 convnet + 0.4 isolation forest",
    plateRows: [
      ["Window", "60 seconds"],
      ["Step", "5 seconds"],
      ["Measure", "once a second"],
      ["Bar", "miss an attack less often"],
    ],
    whyIndex: "03",
    whyTitle: "Why it is built this way",
    reasons: [
      {
        name: "Rates, not counters",
        text: "Each row is one second. Network, disk, and context switches are deltas. Uptime does not drown the model.",
      },
      {
        name: "The window is an image",
        text: "60 seconds by N features. A small CNN reads that heatmap. That is the computer vision part of a host tool.",
      },
      {
        name: "A second opinion",
        text: "Isolation Forest reads the same window as a table: mean, std, max, p95. It catches odd shapes the convnet can miss.",
      },
      {
        name: "Two models, one number",
        text: "0.6 from the convnet, 0.4 from the forest. The bar is set so an attack is missed less often.",
      },
      {
        name: "Aya is ready",
        text: "common, the eBPF programs, the loader, and the execve and openat probes are done. The userspace side (/proc, inotify, file hashes) still sits next to them.",
      },
      {
        name: "Two budgets",
        text: "lite and full profiles. A small VPS and a large VDS do not have to share one load.",
      },
      {
        name: "Console unlock",
        text: "A leaked Telegram token does not by itself open kill or ban. The console still has to unlock the action.",
      },
    ],
    limitsTitle: "Plain limits",
    limits:
      "This is not an antivirus and not a full network IDS. The model is only as good as the normal and anomaly traces recorded on that same machine. A fit from a laptop will not match a busy server.",
    stackIndex: "04",
    stackTitle: "Stack",
    stackLead: "From SysSpectogram. This is the main set.",
    stack: [
      ["Python", "CLI, collect, train, guard"],
      ["PyTorch", "ConvNet on the 60×N heatmap"],
      ["scikit-learn", "Isolation Forest on window stats"],
      ["OpenCV", "PNG heatmaps for alerts"],
      ["NumPy", "Windows and tensors"],
      ["Pandas", "Per-second metric tables"],
      ["Rust", "Integrity agent"],
      ["Aya", "common, eBPF, loader, execve, openat"],
      ["Linux", "/proc, inotify, systemd"],
      ["Docker", "Train and analyze"],
      ["psutil", "Live host counters"],
      ["OSINT", "nmap, DNS, certificate logs"],
    ],
    contactTitle: "Contact",
    contactLead: "GitHub, the project, the browser demo, Telegram.",
    links: {
      github: "https://github.com/lifeqsoll",
      project: "https://github.com/lifeqsoll/SysSpectogram",
      demo: "https://lifeqsoll.github.io/SysSpectogram/demo/",
      telegram: "https://t.me/emosensei",
    },
    linkLabels: {
      github: "github.com/lifeqsoll",
      project: "SysSpectogram",
      demo: "Live demo",
      telegram: "t.me/emosensei",
    },
    readoutT: "t",
    readoutBand: "band",
    readoutAmp: "amp",
  },
  ru: {
    htmlLang: "ru",
    nav: { work: "Work", stack: "Stack", contact: "Contact" },
    heroKicker: "Linux host defense",
    heroTitle: "lifeqsoll",
    heroLead:
      "Занимаюсь компьютерным зрением и делаю инструменты для Linux. Главный из них — SysSpectogram.",
    ctaGithub: "GitHub",
    ctaProject: "SysSpectogram",
    ctaTelegram: "Telegram",
    aboutIndex: "01",
    aboutTitle: "С чем я работаю",
    aboutBody:
      "Компьютерное зрение и модели, которые читают поведение машины. Свёрточные сети, классические модели на таблицах и Linux-обвязка, которая собирает это в одну утилиту для хоста.",
    workIndex: "02",
    workKicker: "MVP",
    workTitle: "SysSpectogram",
    workVersion: "v0.4",
    workLead:
      "Антивирус ловит malware по известному файлу. Майнер на CPU или GPU, подбор пароля к SSH и странный исходящий трафик так обычно не выглядят: файла с сигнатурой нет. SysSpectogram записывает, как ведёт себя машина, складывает минуту в картинку и отвечает, похоже ли это на обычную работу.",
    problemTitle: "В чём смысл",
    problem:
      "Раз в секунду пишутся CPU, память, диск, сеть и GPU. Шестьдесят секунд становятся одной картинкой. Свёрточная сеть смотрит на картинку. Лес изоляции смотрит на ту же минуту как на таблицу. Вместе они говорят, похоже ли это на обычную нагрузку.",
    tasksTitle: "Что она закрывает",
    tasks: [
      "Майнеры и странная нагрузка на CPU, память, диск, сеть и GPU.",
      "Край хоста: подбор пароля, сканы, исходящий трафик, DNS.",
      "Telegram и страница в браузере. Оттуда можно забанить, посмотреть хост или убить процесс. Пока сам не подтвердишь, действие не применяется.",
      "Ответная разведка по IP нападающего: nmap, DNS и журналы сертификатов.",
      "Рядом Rust-агент: процессы, пути, модули, целостность файлов.",
    ],
    plateLabel: "How the number is made",
    plateFormula: "0.6 convnet + 0.4 isolation forest",
    plateRows: [
      ["Window", "60 seconds"],
      ["Step", "5 seconds"],
      ["Measure", "once a second"],
      ["Bar", "miss an attack less often"],
    ],
    whyIndex: "03",
    whyTitle: "Почему так",
    reasons: [
      {
        name: "Rates, не счётчики",
        text: "Каждая строка это одна секунда. Сеть, диск и переключения контекста пишутся как дельта. Uptime не перебивает аномалию.",
      },
      {
        name: "Окно это картинка",
        text: "60 секунд на N признаков. Маленькая CNN смотрит на тепловую карту. Так компьютерное зрение попадает в защиту хоста.",
      },
      {
        name: "Второе мнение",
        text: "Isolation Forest читает то же окно как таблицу: mean, std, max, p95. Ловит форму, которую свёртка может пропустить.",
      },
      {
        name: "Две модели, одно число",
        text: "0,6 от свёрточной сети и 0,4 от леса. Порог стоит так, чтобы атаку пропускали реже.",
      },
      {
        name: "Aya готова",
        text: "common, eBPF-программы, loader и пробы execve и openat уже готовы. Userspace (/proc, inotify, хеши файлов) стоит рядом с ними.",
      },
      {
        name: "Два бюджета",
        text: "Профили lite и full. Маленький VPS и большой VDS не обязаны есть одну и ту же нагрузку.",
      },
      {
        name: "Console unlock",
        text: "Утекший токен Telegram сам по себе не открывает kill и ban. Консоль всё ещё должна разрешить действие.",
      },
    ],
    limitsTitle: "Прямые границы",
    limits:
      "Это не антивирус и не полный NIDS. Модель хороша настолько, насколько хороши normal и anomaly, снятые на этой же машине. С ноутбука она не совпадёт с занятым сервером.",
    stackIndex: "04",
    stackTitle: "Стек",
    stackLead: "Из SysSpectogram. Это основной набор.",
    stack: [
      ["Python", "CLI, collect, train, guard"],
      ["PyTorch", "ConvNet на теплокарте 60×N"],
      ["scikit-learn", "Isolation Forest по статистикам окна"],
      ["OpenCV", "PNG-теплокарты для алертов"],
      ["NumPy", "Окна и тензоры"],
      ["Pandas", "Посекундные таблицы метрик"],
      ["Rust", "Агент целостности"],
      ["Aya", "common, eBPF, loader, execve, openat"],
      ["Linux", "/proc, inotify, systemd"],
      ["Docker", "Train и analyze"],
      ["psutil", "Живые счётчики хоста"],
      ["OSINT", "nmap, DNS, журналы сертификатов"],
    ],
    contactTitle: "Связь",
    contactLead: "GitHub, проект, демо в браузере, Telegram.",
    links: {
      github: "https://github.com/lifeqsoll",
      project: "https://github.com/lifeqsoll/SysSpectogram",
      demo: "https://lifeqsoll.github.io/SysSpectogram/demo/",
      telegram: "https://t.me/emosensei",
    },
    linkLabels: {
      github: "github.com/lifeqsoll",
      project: "SysSpectogram",
      demo: "Live demo",
      telegram: "t.me/emosensei",
    },
    readoutT: "t",
    readoutBand: "band",
    readoutAmp: "amp",
  },
};
