export const copy = {
  en: {
    htmlLang: "en",
    nav: { work: "Work", stack: "Stack", contact: "Contact" },
    heroKicker: "Linux host defense",
    heroTitle: "lifeqsoll",
    heroLead:
      "I study computer vision and build tools for Linux machines. The main one is SysSpectogram.",
    ctaGithub: "GitHub",
    ctaProject: "SysSpectogram",
    ctaTelegram: "Telegram",
    aboutIndex: "01",
    aboutTitle: "What I work on",
    aboutBody:
      "Computer vision, and models that read how a machine behaves. Convnets, classical models on tables, and the Linux tooling that ties them into one host utility.",
    workIndex: "02",
    workKicker: "MVP",
    workTitle: "SysSpectogram",
    workVersion: "v0.6",
    workLead:
      "An antivirus catches malware by a known file. A CPU or GPU miner, SSH password guesses, and odd outgoing traffic usually have no such file. SysSpectogram records how the machine behaves, turns one minute into a picture, and asks whether that minute looks like normal work.",
    problemTitle: "The point",
    problem:
      "Once a second it writes CPU, memory, disk, network, and GPU. Sixty seconds become one image. A small convnet reads the image. An isolation forest reads the same minute as a table. Together they say: this looks like everyday load, or like abuse. On a small VPS it can run without Torch (ONNX / notorch).",
    tasksTitle: "What it takes on",
    tasks: [
      "Miners and odd load on CPU, memory, disk, network, and GPU.",
      "The edge of the host: password guesses, scans, outgoing traffic, DNS.",
      "Telegram and a web page. Ban, kick, kill — only after console unlock. Nothing is applied until you confirm it.",
      "OSINT on the attacker IP: nmap, DNS, and certificate transparency.",
      "Rust agent: processes, paths, modules, eBPF probes, unexpected root, HMAC and exe seal so same-UID noise cannot forge critical alerts.",
    ],
    plateLabel: "How the number is made",
    plateFormula: "0.6 convnet + 0.4 isolation forest",
    plateRows: [
      ["Window", "60 seconds"],
      ["Step", "5 seconds"],
      ["Measure", "once a second"],
      ["Bar", "miss an attack less often"],
    ],
    whyIndex: "03",
    whyTitle: "Why it is built this way",
    reasons: [
      {
        name: "Rates, not counters",
        text: "Each row is one second. Network, disk, and context switches are deltas. Uptime does not drown the model.",
      },
      {
        name: "The window is an image",
        text: "60 seconds by N features. A small CNN reads that heatmap. That is the computer vision part of a host tool.",
      },
      {
        name: "A second opinion",
        text: "Isolation Forest reads the same window as a table: mean, std, max, p95. It catches odd shapes the convnet can miss.",
      },
      {
        name: "Two models, one number",
        text: "0.6 from the convnet, 0.4 from the forest. The bar is set so an attack is missed less often.",
      },
      {
        name: "Aya and the agent path",
        text: "eBPF execve / openat / module probes, userspace /proc watch, HMAC on critical rules, PID allowlist, and an exe seal. Unexpected root is caught in Rust without a second heavy scan on lite VPS.",
      },
      {
        name: "Two budgets",
        text: "lite and full profiles, plus Role Lab packs so a baseline can be trained on a PC and shipped to a VPS.",
      },
      {
        name: "Console unlock",
        text: "A leaked Telegram token does not by itself open kill or ban. The console still has to unlock the action. Kirk auto-isolate stays off until you set allow_ssh_cidrs.",
      },
    ],
    limitsTitle: "Plain limits",
    limits:
      "This is not an antivirus and not a full network IDS. It is not rootkit-proof. The model is only as good as the normal and anomaly traces recorded on that same machine. A fit from a laptop will not match a busy server. Out-of-band VMI is later.",
    stackIndex: "04",
    stackTitle: "Stack",
    stackLead: "From SysSpectogram. This is the main set.",
    stack: [
      ["Python", "CLI, collect, train, guard"],
      ["PyTorch", "ConvNet on the 60×N heatmap"],
      ["scikit-learn", "Isolation Forest on window stats"],
      ["OpenCV", "PNG heatmaps for alerts"],
      ["NumPy", "Windows and tensors"],
      ["Pandas", "Per-second metric tables"],
      ["Rust", "Integrity agent"],
      ["Aya", "eBPF execve, openat, module"],
      ["Linux", "/proc, inotify, systemd"],
      ["ONNX", "Infer without Torch on VPS"],
      ["Docker", "Train and analyze"],
      ["psutil", "Live host counters"],
      ["OSINT", "nmap, DNS, certificate logs"],
    ],
    contactTitle: "Contact",
    contactLead: "GitHub, the project, the browser demo, Telegram.",
    links: {
      github: "https://github.com/lifeqsoll",
      project: "https://github.com/lifeqsoll/SysSpectogram",
      demo: "https://lifeqsoll.github.io/SysSpectogram/demo/",
      telegram: "https://t.me/emosensei",
    },
    linkLabels: {
      github: "github.com/lifeqsoll",
      project: "SysSpectogram",
      demo: "Live demo",
      telegram: "t.me/emosensei",
    },
    readoutT: "t",
    readoutBand: "band",
    readoutAmp: "amp",
  },
  ru: {
    htmlLang: "ru",
    nav: { work: "Work", stack: "Stack", contact: "Contact" },
    heroKicker: "Linux host defense",
    heroTitle: "lifeqsoll",
    heroLead:
      "Занимаюсь компьютерным зрением и делаю инструменты для Linux. Главный из них — SysSpectogram.",
    ctaGithub: "GitHub",
    ctaProject: "SysSpectogram",
    ctaTelegram: "Telegram",
    aboutIndex: "01",
    aboutTitle: "С чем я работаю",
    aboutBody:
      "Компьютерное зрение и модели, которые читают поведение машины. Свёрточные сети, классические модели на таблицах и Linux-обвязка, которая собирает это в одну утилиту для хоста.",
    workIndex: "02",
    workKicker: "MVP",
    workTitle: "SysSpectogram",
    workVersion: "v0.6",
    workLead:
      "Антивирус ловит malware по известному файлу. Майнер на CPU или GPU, подбор пароля к SSH и странный исходящий трафик так обычно не выглядят: файла с сигнатурой нет. SysSpectogram записывает, как ведёт себя машина, складывает минуту в картинку и отвечает, похоже ли это на обычную работу.",
    problemTitle: "В чём смысл",
    problem:
      "Раз в секунду пишутся CPU, память, диск, сеть и GPU. Шестьдесят секунд становятся одной картинкой. Свёрточная сеть смотрит на картинку. Лес изоляции смотрит на ту же минуту как на таблицу. Вместе они говорят, похоже ли это на обычную нагрузку. На маленьком VPS можно без Torch (ONNX / notorch).",
    tasksTitle: "Что она закрывает",
    tasks: [
      "Майнеры и странная нагрузка на CPU, память, диск, сеть и GPU.",
      "Край хоста: подбор пароля, сканы, исходящий трафик, DNS.",
      "Telegram и страница в браузере. Ban, kick, kill — только после console unlock. Пока сам не подтвердишь, действие не применяется.",
      "Ответная разведка по IP нападающего: nmap, DNS и журналы сертификатов.",
      "Rust-агент: процессы, пути, модули, eBPF-пробы, unexpected root, HMAC и seal бинарника, чтобы по одному UID нельзя было подделать критичный алерт.",
    ],
    plateLabel: "How the number is made",
    plateFormula: "0.6 convnet + 0.4 isolation forest",
    plateRows: [
      ["Window", "60 seconds"],
      ["Step", "5 seconds"],
      ["Measure", "once a second"],
      ["Bar", "miss an attack less often"],
    ],
    whyIndex: "03",
    whyTitle: "Почему так",
    reasons: [
      {
        name: "Rates, не счётчики",
        text: "Каждая строка это одна секунда. Сеть, диск и переключения контекста пишутся как дельта. Uptime не перебивает аномалию.",
      },
      {
        name: "Окно это картинка",
        text: "60 секунд на N признаков. Маленькая CNN смотрит на тепловую карту. Так компьютерное зрение попадает в защиту хоста.",
      },
      {
        name: "Второе мнение",
        text: "Isolation Forest читает то же окно как таблицу: mean, std, max, p95. Ловит форму, которую свёртка может пропустить.",
      },
      {
        name: "Две модели, одно число",
        text: "0,6 от свёрточной сети и 0,4 от леса. Порог стоит так, чтобы атаку пропускали реже.",
      },
      {
        name: "Aya и путь агента",
        text: "eBPF-пробы execve / openat / module, userspace /proc, HMAC на критичных правилах, PID allowlist и seal бинарника. Unexpected root ловится в Rust без второго тяжёлого обхода на lite VPS.",
      },
      {
        name: "Два бюджета",
        text: "Профили lite и full плюс Role Lab: базовую линию можно собрать на ПК и отдать на VPS.",
      },
      {
        name: "Console unlock",
        text: "Утекший токен Telegram сам по себе не открывает kill и ban. Консоль всё ещё должна разрешить действие. Kirk auto-isolate выключен, пока не заданы allow_ssh_cidrs.",
      },
    ],
    limitsTitle: "Прямые границы",
    limits:
      "Это не антивирус и не полный NIDS. Это не защита от руткитов. Модель хороша настолько, насколько хороши normal и anomaly, снятые на этой же машине. С ноутбука она не совпадёт с занятым сервером. Out-of-band VMI позже.",
    stackIndex: "04",
    stackTitle: "Стек",
    stackLead: "Из SysSpectogram. Это основной набор.",
    stack: [
      ["Python", "CLI, collect, train, guard"],
      ["PyTorch", "ConvNet на теплокарте 60×N"],
      ["scikit-learn", "Isolation Forest по статистикам окна"],
      ["OpenCV", "PNG-теплокарты для алертов"],
      ["NumPy", "Окна и тензоры"],
      ["Pandas", "Посекундные таблицы метрик"],
      ["Rust", "Агент целостности"],
      ["Aya", "eBPF execve, openat, module"],
      ["Linux", "/proc, inotify, systemd"],
      ["ONNX", "Инференс без Torch на VPS"],
      ["Docker", "Train и analyze"],
      ["psutil", "Живые счётчики хоста"],
      ["OSINT", "nmap, DNS, журналы сертификатов"],
    ],
    contactTitle: "Связь",
    contactLead: "GitHub, проект, демо в браузере, Telegram.",
    links: {
      github: "https://github.com/lifeqsoll",
      project: "https://github.com/lifeqsoll/SysSpectogram",
      demo: "https://lifeqsoll.github.io/SysSpectogram/demo/",
      telegram: "https://t.me/emosensei",
    },
    linkLabels: {
      github: "github.com/lifeqsoll",
      project: "SysSpectogram",
      demo: "Live demo",
      telegram: "t.me/emosensei",
    },
    readoutT: "t",
    readoutBand: "band",
    readoutAmp: "amp",
  },
};
